
@startuml
'https://plantuml.com/sequence-diagram

autonumber

A --> B: Создать сканер \n и прочитать n; \n (Cодержит инициализацию \n сканера и чтение)
B --> C: Закрываем сканнер;
C --> D: Заявляем int[] f = new int[n]; \n (Оголошення и \n инициализация массива)
D --> E: f[0] = 0; \n (Инициализация \n первого массива)
E --> F: [f[1] = 1]; \n (Инициализация \n второго массива)
F --> G: Для значений от 2 до n-1;
G --> H: Так f[i] = f[i-1] + f[i-2]; \n (Вычисление очередного \n числа Фибоначчи)
H --> G: ;
G --> I: Нет, Для значений от 2 до n-1; \n (налогично для второго \n цикла вывода)
I --> J: Да, вывести "F(" + i + ") = " + f[i];
J --> I: ;
I --> K: Если "Нет"; (<- то Закончить)
@enduml